[package]
name = "minitt"
version = "0.2.0"
authors = ["ice1000 <ice1000kotlin@foxmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Mini-TT, a dependently-typed lambda calculus, extended and implementated in Rust"
readme = "README.md"
categories = ["development-tools"]
documentation = "https://docs.rs/minitt"
repository = "https://github.com/owo-lang/minitt-rs"

[badges]
appveyor = { repository = "owo-lang/minitt-rs", service = "github" }
circle-ci = { repository = "owo-lang/minitt-rs", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "owo-lang/minitt-rs" }
is-it-maintained-open-issues = { repository = "owo-lang/minitt-rs" }

[dependencies]
pest = { version = "2.1.0", optional = true }
pest_derive = { version = "2.1.0", optional = true }
clap = { version = "2.32.0", features = ["wrap_help"], optional = true }
structopt = { version = "0.2", optional = true }
rustyline = { version = "3.0.0", optional = true }

[features]
default = ["pretty", "parser"]
pretty = []
parser = ["pest", "pest_derive"]
cli = ["clap", "structopt", "rustyline"]

[lib]
name = "minitt"
path = "src/lib.rs"

[[bin]]
name = "minittc"
path = "src/main.rs"
required-features = ["cli", "parser", "pretty"]
