[package]
name = "minitt"
version = "0.1.2"
authors = ["ice1000 <ice1000kotlin@foxmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Mini-TT, a dependently-typed lambda calculus, implementated in Rust"
readme = "README.md"
categories = ["development-tools"]

[badges]
appveyor = { repository = "ice1000/minitt-rs", service = "github" }
circle-ci = { repository = "ice1000/minitt-rs", branch = "master" }
maintenance = { status = "passively-maintained" }

[features]
default = ["pretty"]
pretty = []
